## roles/ansible-role-pihole/tasks/main.yml
# vim:ft=yaml.ansible:
---
- name: "Disable WiFi and Bluetooth"
  copy:
    src: raspi-blacklist.conf
    dest: /etc/modprobe.d/raspi-blacklist.conf
    mode: 0600
  tags: pihole,admin

- name: "Download Pi-Hole Installer"
  get_url:
    url: https://raw.githubusercontent.com/pi-hole/pi-hole/master/automated%20install/basic-install.sh
    dest: /tmp/install-pihole.sh
    mode: 0740
    validate_certs: no
  tags: pihole

- name: "Ensure pihole group exists"
  group:
    name: '{{ pihole_user }}'
    state: present
  tags: pihole,admin

- name: "Ensure pihole user exists"
  user:
    name: pihole
    comment: Pihole User
    shell: /bin/bash
    group: '{{ pihole_user }}'
  tags: pihole,admin

- name: "Create pihole configuration directory"
  file:
    name: '{{ pihole_config }}'
    state: directory
    owner: '{{ pihole_user }}'
    group: '{{ pihole_user }}'
    mode: 0755
  tags: pihole

- name: "Create pihole configuration"
  template:
    src: setupVars.conf.j2
    dest: '{{ pihole_config }}/setupVars.conf'
    owner: root
    group: root
    mode: 0644
  tags: pihole

- name: "Set static IP configuration"
  template:
    src: "etc_network_interfaces.j2"
    dest: "/etc/network/interfaces"
    owner: root
    group: root
    mode: 0644
  tags: pihole

- name: "Set default DNS"
  template:
    src: "etc_resolv.conf.j2"
    dest: "/etc/resolv.conf"
    owner: root
    group: root
    mode: 0644
  tags: pihole,admin

- name: "Install Pi-Hole"
  command: "/tmp/install-pihole.sh --unattended"
  register: install_pihole
  tags: pihole

- name: "Set static IP configuration"
  template:
    src: "etc_network_interfaces.j2"
    dest: "/etc/network/interfaces"
    owner: root
    group: root
    mode: 0644
  tags: pihole

- name: "Set PiHole to update weekly"
  replace:
    path: /etc/cron.d/pihole
    regexp: '^#(.*updatePihole.*)$'
    replace: '\1'
    backup: yes
  tags: pihole,admin

- name: "Reboot"
  reboot:
    reboot_timeout: 600
  tags: pihole,admin



...
